// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VueValidation.Data;

namespace VueValidation.Migrations
{
    [DbContext(typeof(CustomerContext))]
    [Migration("20190422080047_InitialCustomer")]
    partial class InitialCustomer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VueValidation.Data.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine1");

                    b.Property<string>("AddressLine2");

                    b.Property<string>("CityTown");

                    b.Property<string>("CompanyName");

                    b.Property<string>("ContactName");

                    b.Property<string>("Country");

                    b.Property<string>("Phone");

                    b.Property<string>("PostalCode");

                    b.Property<string>("StateProvince");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine1 = "123 Main Street",
                            CityTown = "Atlanta",
                            CompanyName = "Wilder Minds LLC",
                            ContactName = "Shawn Wildermuth",
                            Country = "USA",
                            Phone = "404-555-1212",
                            PostalCode = "12345",
                            StateProvince = "GA"
                        },
                        new
                        {
                            Id = 2,
                            AddressLine1 = "123 Main Street",
                            CityTown = "Atlanta",
                            CompanyName = "Hello World Film",
                            ContactName = "Jake Smith",
                            Country = "USA",
                            Phone = "404-555-1212",
                            PostalCode = "12345",
                            StateProvince = "GA"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
